import type { Metadata, Viewport } from "next";
import localFont from "next/font/local";
import "./globals.css";
import DeviceSettingBack from "@/commons/settings/08-01-device-setting-back";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// 뷰포트 설정 - 모바일 웹뷰에서 핀치 줌 기능 제어
//
// 기본 설정 (핀치 줌 비활성화):
// 1. width: "device-width" - 디바이스 너비에 맞춤
// 2. initialScale: 1 - 초기 확대/축소 비율 1배
// 3. maximumScale: 1 - 최대 확대 비율 1배 (확대 불가)
// 4. userScalable: false - 사용자 확대/축소 비활성화
//
// 특정 페이지에서 동적으로 변경:
// - 전체화면 이미지 뷰어: maximumScale=3.0, userScalable=true
// - 일반 페이지: maximumScale=1.0, userScalable=false
export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  minimumScale: 1, // 축소 불가
  maximumScale: 1,
  userScalable: false,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <DeviceSettingBack>{children}</DeviceSettingBack>
      </body>
    </html>
  );
}
